version: '3'

services:
  postgres:
    image: 'postgres:14.13'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: local_db
    ports:
      - '5433:5432'
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build:
      context: ../..
      dockerfile: 'deployment/local/Dockerfile'
    depends_on:
      - postgres
    command: bash deployment/local/init.sh
    env_file: ./.env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=$${DEBUG)
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
